### ISSUE TITLE
No error when dumpfile exists

### ISSUE THREAD

**Issue by dodijk** [semanticize/st#3]
When using --download and a Wikipedia dump already exists, no output is given by semanticizest-dumpparser.

**Comment by larsmans** [comment]
So what is the output exactly? I find this strange, because the dump file is opened with

```
os.OpenFile(filepath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0666)
```

and the error seems to be checked all the way up the call chain.

**Comment by dodijk** [comment]
It is easily reproducable, by calling
`$GOPATH/bin/semanticizest-dumpparser --download=enwiki enwiki.model`
then CTRL-C'ing after a bit of downloading and running the same command again.

**Comment by larsmans** [comment]
Confirmed. Older versions gave

```
dumpparser 2015/06/26 11:20:51 open enwiki-latest-pages-articles.xml.bz2: file exists
```

which is the intended output.
