### ISSUE TITLE
Model for nlwiki-20150602 does not complete

### ISSUE THREAD

**Issue by dodijk** [semanticize/st#4]
The number of processed articles stops increasing after nearly 500k. 

`dumpparser 2015/06/26 11:02:54 processed 493622 articles
dumpparser 2015/06/26 11:03:09 processed 493622 articles`

With a different number of processes it's a bit less:
`dumpparser 2015/06/26 11:33:00 processed 492734 articles`

Reproduce with (before a new dump becomes available):
`$GOPATH/bin/semanticizest-dumpparser --download=nlwiki nlwiki.model`

**Comment by larsmans** [comment]
Unable to reproduce: dumpparser runs to completion in ~20mins. Could it be that your dump file is corrupted somehow, and the error isn't reported because of #3?

**Comment by dodijk** [comment]
Unable to reproduce here to. Let's assume it is solved because of #3.
